# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e587deaa885aa18167cfa19cb0a3290426b7de6e6992b19f2342c5a78088574d5c5e0170d934e0e1fa9f19fc77e13e66f1e71a312c1443a8e82e9c303a5d02b

test:
  secret_key_base: 10ba40c8a08609b19d1ba130844d8082d143a4e40666adc9f710c69d3589e7c5df478840adfe047401f7bc9219131bbae1820ff72528dc383f37c2ce8e7ddc68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
